# Neovim default dark color scheme for kitty terminal emulator
#
# Based on Neovim's built-in highlight groups in highlight_group.c.
#
# https://github.com/neovim/neovim/blob/82ea5a8aac40331579113b961b6cef88865ad5a9/src/nvim/highlight_group.c#L2960

foreground #e0e2ea
background #14161b

# Black
color0 #07080d
color8 #4f5258

# Red
color1 #ffc0b9
color9 #ffc0b9

# Green
color2  #b3f6c0
color10 #b3f6c0

# Yellow
color3  #fce094
color11 #fce094

# Blue
color4  #a6dbff
color12 #a6dbff

# Magenta
color5  #ffcaff
color13 #ffcaff

# Cyan
color6  #8cf8f7
color14 #8cf8f7

# White
color7  #9b9ea4
color15 #eef1f8

# Cursor
cursor #eef1f8
cursor_text_color #07080d

# Selection highlight (Visual)
selection_foreground none
selection_background #4f5258

# The color for highlighting URLs on mouse-over (Underlined)
url_color #e0e2ea

# Window borders
active_border_color #a6dbff
inactive_border_color #07080d
bell_border_color #fce094

# Tab bar
tab_bar_style fade
tab_fade 1
active_tab_foreground   #e0e2ea
active_tab_background   #4f5258
active_tab_font_style   bold
inactive_tab_foreground #9b9ea4
inactive_tab_background #2c2e33
inactive_tab_font_style bold
tab_bar_background #07080d

# Title bar
macos_titlebar_color #14161b
