### toggle-pane.yazi

[[mgr.prepend_keymap]]
on   = "="
run  = "plugin toggle-pane max-preview"
desc = "[toggle-pane] Maximize or restore the preview pane"


### zoom.yazi

# [[mgr.prepend_keymap]]
# on   = "+"
# run  = "plugin zoom 1"
# desc = "Zoom in hovered file"
#
# [[mgr.prepend_keymap]]
# on   = "-"
# run  = "plugin zoom -1"
# desc = "Zoom out hovered file"


# Smart enter

[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = "plugin smart-enter"
desc = "[smart-enter] Enter the child directory, or open the file"



# Forward and back

[[mgr.prepend_keymap]]
on   = [ "<C-o>" ]
run  = "back"
desc = "[User] Back to previous directory"

[[mgr.prepend_keymap]]
on   = [ "<C-i>" ]
run  = "forward"
desc = "[User] Forward to next directory"



# Quick look

[[mgr.prepend_keymap]]
on = "<C-p>"
run = "shell -- qlmanage -p %s"
desc = "[User] Quick look"



[[mgr.prepend_keymap]]
on   = [ "T" ]
run  = "tab_create"
desc = "[User] Create tab at default directory"

[[mgr.prepend_keymap]]
on   = [ "q" ]
run  = "close"
desc = "[User] Close the current tab, or quit if it's the last"

[[mgr.prepend_keymap]]
on   = [ "<C-c>" ]
run  = "quit"
desc = "[User] Quit the process"

[[mgr.prepend_keymap]]
on   = [ "j" ]
run  = "arrow 1"
desc = "[User] Down without wrap-around"

[[mgr.prepend_keymap]]
on   = [ "k" ]
run  = "arrow -1"
desc = "[User] Up without wrap-around"

[[mgr.prepend_keymap]]
on   = [ "<Space>" ]
run  = "cd --interactive"
desc = "[User] Goto file"

[[mgr.prepend_keymap]]
on   = [ "o" ]
run  = "shell -- open %s"
desc = "[User] Open with default program"



# Remotes

[[mgr.prepend_keymap]]
on   = [ "g", "u" ]
run  = "cd sftp://uaptt"
desc = "[Remote] Connect to uaptt"

[[mgr.prepend_keymap]]
on   = [ "g", "b" ]
run  = "cd sftp://bora"
desc = "[Remote] Connect to bora"

[[mgr.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd sftp://air"
desc = "[Remote] Connect to air"
