[sftp.v]
host = "biquando-v"
user = "biqua"
port = 22
key_file = "~/.ssh/id_rsa"

[sftp.bora]
host = "bora.cs.ucla.edu"
user = "biquando"
port = 22
key_file = "~/.ssh/id_rsa"

[sftp.air]
host = "biquando-air.local"
user = "biqua"
port = 22
key_file = "~/.ssh/id_rsa"
