[opener]
play = [
    { run = 'open %s', desc = "Play", orphan = true, for = "macos" }
]

[mgr]
show_hidden = false

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

# This doesn't seem to work
[[plugin.prepend_previewers]]
url = "~/mnt/**"
run = "noop"

[[plugin.prepend_preloaders]]
url = "~/mnt/**"
run = "noop"

[preview]
max_width  = 1000
max_height = 1000
