[opener]
play = [
    { run = 'open "$@"', desc = "Play", orphan = true, for = "macos" }
]

[manager]
show_hidden = false

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
